import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import SmoothScroll from "@/components/layout/SmoothScroll";
import { useGSAP } from "@gsap/react";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { ScrollSmoother } from "gsap/ScrollSmoother";
// import { LoadingProvider } from "../components/common/LoadingContext";
// import LoadingOverlay from "../components/animations/LoadingOverlay";
import ClientLayoutWrapper from "../components/layout/ClientLayoutWrapper";
import TransitionCurtain from "../components/animations/PageTransition";


if (typeof window !== 'undefined') {
  gsap.registerPlugin(ScrollTrigger, ScrollSmoother, useGSAP);
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="is-loading">
      <body>        
        {/* <LoadingProvider> */}
          <TransitionCurtain/>
          {/* <LoadingOverlay /> */}
          <Header />
          <SmoothScroll>
            <ClientLayoutWrapper>
              {children}
            </ClientLayoutWrapper>
          </SmoothScroll>
        {/* </LoadingProvider> */}
      </body>
    </html>
  );
}
