import { ReactLenis } from 'lenis/react'
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import SmoothScroll from "@/components/layout/SmoothScroll";
import ScrollRestoration from '@/components/layout/ScrollRestoration';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        {/* Main Content */}
        

        <ScrollRestoration />
        {/* <SmoothScroll> */}
          <Header />
          <main className="content">{children}</main>
          <Footer /> 
        {/* </SmoothScroll> */}
      </body>
    </html>
  );
}
